# Generated by Django 4.0.2 on 2022-03-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelvar',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
