# Generated by Django 4.0.2 on 2022-04-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelvar',
            name='percent_value',
            field=models.IntegerField(default='0'),
        ),
    ]
