# Generated by Django 3.2.8 on 2022-03-08 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelvar',
            name='status',
        ),
    ]
