# Generated by Django 3.2.8 on 2021-10-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.IntegerField(default='', max_length=11)),
                ('quantity', models.IntegerField(default='', max_length=11)),
                ('unit_type', models.IntegerField(default='', max_length=11)),
                ('vechicle', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('price', models.FloatField(default='', max_length=255)),
                ('price_total', models.FloatField(default='', max_length=255)),
            ],
        ),
    ]
