# Generated by Django 3.2.8 on 2021-11-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_inventories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Released',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('file', models.ImageField(blank=True, null=True, upload_to='profilepic/')),
                ('name', models.CharField(default='', max_length=255)),
                ('refrence', models.CharField(default='', max_length=255)),
                ('vin', models.CharField(default='', max_length=255)),
                ('make', models.CharField(default='', max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('note', models.TextField()),
            ],
        ),
    ]
