# Generated by Django 3.2.8 on 2021-11-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211118_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='rfc',
            field=models.CharField(default='', max_length=255),
        ),
    ]
