# Generated by Django 3.2.8 on 2022-03-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_modelvar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelvar',
            name='created_at',
        ),
        migrations.AddField(
            model_name='modelvar',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
    ]
