# Generated by Django 4.0.2 on 2022-05-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_modelname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelname',
            name='modelname',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
