# Generated by Django 4.0.2 on 2022-02-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_terms_and_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='membershipstatus',
            field=models.IntegerField(null=True),
        ),
    ]
