# Generated by Django 3.2.9 on 2021-11-19 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211119_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='file',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='insurance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insurance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
