# Generated by Django 3.2.8 on 2021-11-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customer_rfc'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipper_exports',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shipper_exports',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
