# Generated by Django 3.2.8 on 2021-12-20 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userpermission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company'),
        ),
    ]
