# Generated by Django 3.2.8 on 2021-11-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='released',
            name='paid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
