# Generated by Django 3.2.9 on 2021-11-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211119_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipper_exports',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shipper_exports',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
