# Generated by Django 3.2.9 on 2021-11-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='policy_number',
            field=models.CharField(default='', max_length=255),
        ),
    ]
