# Generated by Django 4.0.2 on 2022-05-13 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_var_selectvar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectvar',
            name='varid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.var'),
        ),
    ]
