# Generated by Django 3.2.9 on 2021-11-21 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211120_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipper_exports',
            name='its_paid',
            field=models.CharField(default='', max_length=255),
        ),
    ]
