# Generated by Django 3.2.8 on 2021-11-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211118_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
