# Generated by Django 3.2.8 on 2021-11-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211119_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='released',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='released',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='temporary_permits',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='temporary_permits',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
