# Generated by Django 3.2.9 on 2021-11-21 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_shipper_exports_its_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipper_exports',
            name='its_paid',
        ),
    ]
