# Generated by Django 3.2.8 on 2021-11-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211120_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='released',
            name='paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shipper_exports',
            name='paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='temporary_permits',
            name='paid',
            field=models.IntegerField(default=0),
        ),
    ]
