# Generated by Django 3.2.9 on 2021-11-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_shipper_exports_its_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipper_exports',
            name='its_paid',
            field=models.CharField(default='', max_length=255),
        ),
    ]
