# Generated by Django 3.2.8 on 2021-11-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_released_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.IntegerField()),
                ('model_type', models.CharField(default='', max_length=255)),
                ('file', models.CharField(default='', max_length=255)),
                ('size', models.CharField(default='', max_length=255)),
                ('type_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='pedimentos',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='profilepic/'),
        ),
        migrations.AddField(
            model_name='pedimentos',
            name='lock1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pedimentos',
            name='lock2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pedimentos',
            name='lock3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pedimentos',
            name='lock4',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pedimentos',
            name='lock5',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pedimentos',
            name='lock6',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pedimentos',
            name='lock7',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pedimentos',
            name='lock8',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pedimentos',
            name='remarks',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pedimentos',
            name='supplier',
            field=models.CharField(default='', max_length=255),
        ),
    ]
