# Generated by Django 4.0.5 on 2022-07-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_modelvar_percent_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelvar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='modelvar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
