# Generated by Django 3.2.8 on 2021-11-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211120_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedimentos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pedimentos',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
