# Generated by Django 3.2.8 on 2021-11-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211112_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipper_exports',
            name='itn',
            field=models.CharField(default='', max_length=255),
        ),
    ]
