# Generated by Django 3.2.9 on 2021-11-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_shipper_exports_its_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipper_exports',
            name='paid',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
