# Generated by Django 4.0.5 on 2022-07-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_modelvar_created_at_modelvar_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelname',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='modelname',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='modelvar',
            name='modelname_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='modelvar',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
