# Generated by Django 4.0.5 on 2022-07-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_modelname_created_at_modelname_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelname',
            name='modelname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
