# Generated by Django 3.2.8 on 2021-11-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211122_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipper_exports',
            name='year',
            field=models.IntegerField(default='', max_length=4),
        ),
    ]
