# Generated by Django 3.2.9 on 2021-11-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_shipper_exports_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipper_exports',
            name='paid',
            field=models.CharField(choices=[(0, 'Inactive'), (1, 'Active')], default=0, max_length=100),
        ),
    ]
