# Generated by Django 3.2.8 on 2021-11-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_insurance_policy_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='policy_number',
            field=models.CharField(default='', max_length=255),
        ),
    ]
