# Generated by Django 3.2.9 on 2021-11-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_shipper_exports_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipper_exports',
            name='paid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
