# Generated by Django 3.2.8 on 2021-11-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='released',
            name='scan',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='passport_upload',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
