# Generated by Django 3.2.8 on 2021-11-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20211124_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporary_permits',
            name='permit_year',
            field=models.IntegerField(default='', max_length=4),
        ),
    ]
