# Generated by Django 3.2.8 on 2021-12-09 11:58

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20211209_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, default='', help_text='Contact phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[('superadmin', 0), ('provider', 1), ('user', 2)], default='2'),
        ),
    ]
