# Generated by Django 3.2.8 on 2021-12-10 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20211209_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agencies',
            old_name='user_id',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='user_id',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='insurance',
            old_name='user_id',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='pedimentos',
            old_name='user_id',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='released',
            old_name='user_id',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='shipper_exports',
            old_name='user_id',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='temporary_permits',
            old_name='user_id',
            new_name='created_by',
        ),
    ]
