# Generated by Django 3.2.8 on 2021-12-15 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='userPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipper_Exports', models.IntegerField(default=1)),
                ('pedimentos', models.IntegerField(default=1)),
                ('temporary_Permits', models.IntegerField(default=1)),
                ('customer', models.IntegerField(default=1)),
                ('insurance', models.IntegerField(default=1)),
                ('released', models.IntegerField(default=1)),
                ('agencies', models.IntegerField(default=1)),
                ('providers', models.IntegerField(default=1)),
                ('title', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
