# Generated by Django 3.2.8 on 2021-12-16 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_userpermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermission',
            name='title',
        ),
    ]
