# Generated by Django 3.2.8 on 2021-12-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_userpermission_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpermission',
            old_name='agencies',
            new_name='catalogs',
        ),
        migrations.RenameField(
            model_name='userpermission',
            old_name='providers',
            new_name='reports',
        ),
        migrations.AddField(
            model_name='userpermission',
            name='validate',
            field=models.IntegerField(default=1),
        ),
    ]
